# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Nylox. <https://github.com/nylox/nylox.git>
#
#    Nylox is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nylox is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nylox.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "Install packages"
  vars:
    packages: "{{ conf.packages }}"
  include_tasks: "{{ role_path }}/../common/tasks/{{ ansible_pkg_mgr }}/package.yml"
  tags:
  - bin

- name: "Stop service"
  service:
    name:    "{{ item }}"
    state:   stopped
    enabled: no
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Deploy '{{ ansible_pkg_mgr }}' based configuration"
  template:
    src:   "{{ ansible_pkg_mgr }}/{{ item.name }}.j2"
    dest:  "{{ item.path }}/{{ item.name }}"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "{{ conf.files }}"
  tags:
  - conf

- name: "Delete logging directory"
  file:
    dest:  "{{ item }}"
    state: absent
  with_items:
  - "/var/log/redis"
  tags:
  - clear

- name: "Create logging directory"
  file:
    dest:  "{{ item }}"
    state: directory
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rwx,g=rx,o=rx"
  with_items:
  - "/var/log/redis"
  tags:
  - conf

- name: "Create log file"
  copy:
    dest: "/var/log/redis/redis.log"
    content: "--- Empty log file ---"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode: "u=rwx,g=rwx,o=rx"
  tags:
  - conf

- name: "Final state for service - {{ service_final.state }}"
  service:
    name:    "{{ item }}"
    state:   "{{ service_final.state }}"
    enabled: "{{ service_final.enabled }}"
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Wait for ports"
  wait_for:
    host:    "{{ item.host }}"
    port:    "{{ item.port }}"
    state:   started
    timeout: 30
  with_items:
  - host: "{{ bind_host | d('127.0.0.1') }}"
    port: "{{ bind_port | d('6379') }}"
  loop_control:
    label: "{{ item.host }}:{{ item.port }}"
  when:
  - "service_final.state != 'stopped'"
  tags:
  - service
  - verify

