# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Nylox. <https://github.com/nylox/nylox.git>
#
#    Nylox is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nylox is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nylox.  If not, see <http://www.gnu.org/licenses/>.
#

---
# TODO add group
- name: "Add user '{{ conf.username }}'"
  user:
    name:  "{{ conf.username }}"
    state: present
  tags:
  - conf

- name: "Extract archive"
  unarchive:
    src:  "{{ consul_archive_binary }}"
    dest: /usr/bin
    mode: "u=rwx,g=rx,o=rx"
  tags:
  - bin

- name: "Create 'webui' directory"
  file:
    path:  /opt/consul/ui/dist
    state: directory
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
  when:
  - "consul_config_mode == 'server'"
  tags:
  - bin 

- name: "Extract webui archive '{{ consul_archive_webui }}'"
  unarchive:
    src:   "{{ consul_archive_webui }}"
    dest:  /opt/consul/ui/dist
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rwx,g=rx,o=rx"
  when:
  - "consul_config_mode == 'server'"
  tags:
  - bin

- name: "Deploy service file"
  template:
    src:   consul_systemd.j2
    dest:  /etc/systemd/system/consul.service
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  tags:
  - service

- name: "Stop service"
  service:
    name:    "{{ item }}"
    state:   stopped
    enabled: no
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Delete configuration directories"
  file:
    dest:  "{{ item }}"
    state: absent
  with_items:
  - "{{ conf.conf_dir }}"
  - "{{ conf.root_dir }}"
  - /var/consul/raft/peers.json
  - /var/consul/raft/raft.db
  - /var/consul/serf/local.keyring
  - /var/consul/raft/snapshots
  tags:
  - clear

- name: "Delete previous snapshot files"
  file:
    path:  "{{ item }}"
    state: absent
  with_fileglob:
  - /var/consul/raft/snapshots/*
  tags:
  - clear

- name: "Create configuration directories"
  file:
    path:  "{{ item }}"
    state: "directory"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
  with_items:
  - "{{ conf.conf_dir }}"
  - "{{ conf.conf_dir }}/ssl"
  - "{{ conf.root_dir }}"
  - /var/log/consul
  - /var/consul
  - /var/consul/raft/snapshots
  tags:
  - conf

- name: "Deploy configuration"
  template:
    src:   "{{ conf.conf_file }}.j2"
    dest:  "{{ conf.conf_dir }}/{{ conf.conf_file }}"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  tags:
  - conf

- name: "Deploy watches configuration"
  template:
    src:   "{{ item }}.j2"
    dest:  "{{ conf.root_dir }}/{{ item }}"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "watches.json"
  tags:
  - conf

- name: "Deploy daemon additional configuration"
  template:
    src:   "service.json.j2"
    dest:  "{{ conf.root_dir }}/svc_{{ iteritem }}.json"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode:  "u=rw,g=r,o=r"
    force: yes
  with_items:
  - "{{ lb_services.keys() | sort }}"
  loop_control:
    loop_var: "iteritem"
  when:
  - lb_services[iteritem].apply_to | default('') in group_names
  tags:
  - conf

- name: "Verify configuration"
  shell:
    consul validate {{ item }}
  with_items:
  - "{{ conf.conf_dir }}"
  - "{{ conf.root_dir }}"
  tags:
  - verify

- name: "Deploy consul-watcher-utils"
  template:
    src: "{{ item }}"
    dest: "/usr/bin/cwu"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
    force: yes
  with_items:
  - "consul-watcher-utils"
  tags:
  - conf

- name: "Final state for service - {{ service_final.state }}"
  service:
    name:    "{{ item }}"
    state:   "{{ service_final.state }}"
    enabled: "{{ service_final.enabled }}"
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Wait for ports - server ports"
  wait_for:
    host:    "{{ item.host }}"
    port:    "{{ item.port }}"
    state:   started
    timeout: 5
  with_items:
  - host: "{{ bind_host }}"
    port: "8300"
  - host: "{{ bind_host }}"
    port: "8302"
  loop_control:
    label: "{{ item.host }}:{{ item.port }}"
  when:
  - "service_final.state != 'stopped'"
  - "consul_config_mode == 'server'"
  tags:
  - service
  - verify

- name: "Wait for ports - all Consul nodes ports"
  wait_for:
    host:    "{{ item.host }}"
    port:    "{{ item.port }}"
    state:   started
    timeout: 5
  with_items:
  - host: "{{ bind_host }}"
    port: "8301"  
  - host: "{{ bind_host }}"
    port: "8500"
  - host: "{{ bind_host }}"
    port: "8600"
  loop_control:
    label: "{{ item.host }}:{{ item.port }}"
  when:
  - "service_final.state != 'stopped'"
  tags:
  - service
  - verify

- name: "Join cluster via primary node '{{ primary_node }}'"
  vars:
    primary_node: "{{ groups['consul-nodes'][0] }}"
  shell:
    "{{ item }}"
  with_items:
  - "/usr/bin/consul join {{ primary_node }}"
  when:
  - not is_primary
  tags:
  - service


- name: "Deploy LB key files"
  uri:
    url: "http://{{ bind_host }}:8500/v1/kv/{{ item }}"
    method: PUT
#    user: your_username
#    password: your_pass
#    body: "{{ lookup('file','issue.json') }}
#    force_basic_auth: yes
    status_code: 200
#    body_format: json
  with_items:
  - "{{ lb_keys | list | unique | sort }}"
  when:
  - is_primary
  tags:
  - init

#- name: "Create kv inventory"
#  set_fact:
#    kv_inventory: |
#      {% set prefix = 'inventory' %}
#      {% set keys = '' %}
#      {{ (keys) }}

- name: "Delete LB key inventory"
  uri:
    url: "http://{{ bind_host }}:8500/v1/kv/inventory"
    method: DELETE
    status_code: 200
  when:
  - is_primary
  tags:
  - init
  - clear

- name: "Deploy LB key inventory groups"
  uri:
    url: "http://{{ bind_host }}:8500/v1/kv/inventory/groups/{{ item }}"
    method: PUT
    body: "{{ groups[item] | to_nice_json(indent=2) }}"
    status_code: 200
    body_format: json
  with_items:
  - "{{ groups | list | unique | sort }}"
  when:
  - is_primary
  tags:
  - init

- name: "Deploy LB key inventory nodes"
  uri:
    url: "http://{{ bind_host }}:8500/v1/kv/inventory/nodes/{{ item }}"
    method: PUT
    body: "{{ hostvars[item] | to_nice_json(indent=2) }}"
    status_code: 200
    body_format: json
  with_items:
  - "{{ groups['all'] | list | unique | sort }}"
  when:
  - is_primary
  tags:
  - init
